### PR TITLE
Adding jupyter notebook

### PR DESCRIPTION
**Pull request by Staneesh**
* Added simple jupyter notebook file
* Added the list of requirements
* Extended the README file with instructions for running the code
* Added the gitignore file to skip tracking `venv` directory

### CODE REVIEW

**Comment by Staneesh** [comment]
Let's merge this only after #3 gets merged to keep the pull request history clean.

**Review by ibaranochnikov — APPROVED** [review]
It looks ok

**Comment by afoster28** [comment]
Basics created for subsequent work - OK

**Review by afoster28 — APPROVED** [review]
Changes OK

**Pull request merged**
